#!/usr/bin/env bash

if command -v pyenv; then
    py_version=$(pyenv install --list | \grep -vE "\-|rc" | \grep " 3\.[678]" | tail -n 1 | awk '{$1=$1};1')

    pyenv install "$py_version"
    pyenv global "$py_version"
    echo "Installed Python $py_version"
else
    echo "pyenv not installed"
    echo "brew install pyenv pyenv-virtualenv pyenv-virtualenvwrapper"
    exit 1
fi
